//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALCULADORA
    {
        public int ID_calculadora { get; set; }
        public string ORIGEN { get; set; }
        public string DESTINO { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<decimal> LIBRAS { get; set; }
        public Nullable<decimal> VALOR { get; set; }
    }
}
